apiVersion: v1
kind: Pod
metadata:
  name: expense-tracker-iot-fake-device
  labels:
    app: expense-tracker-iot-fake-device
spec:
  containers:
  - name: expense-tracker-iot-fake-device
    image: us.icr.io/nyu-cc/expense-tracker-iot-fake-device:latest
    env:
    - name: HOST
      value: "184.173.52.86"
    - name: PORT
      value: "30002"
    - name: TOPIC
      value: "home_device"
    - name: USER_NAME
      value: "Zelong"
    - name: DEVICE_NAME
      value: "bedroom-bulb"
    - name: INTERVAL
      value: "3600"